version: '3.8'
services:

    website:
      build:
        context: ./deploy
        dockerfile: Dockerfile
      ports:
        - '8082:80'
        - '443:443'
      volumes:
        - ./website/.next/static:/var/www/html
        - ./deploy/nginx.conf:/etc/nginx/site-available/default
      